name: Build and Scan Image

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t bsapp:latest .

      - name: Tag Docker Image
        run: |
          docker tag bsapp:latest setthapong/bsapp:latest

      - name: Scan Image with Twistlock
        uses: ./.github/actions/image-scan
        with:
          tl-username: ${{ secrets.TL_USERNAME }}
          tl-password: ${{ secrets.TL_PASSWORD }}
          tl-console-url: ${{ secrets.TL_CONSOLE_URL }}
          tl-cli-version: "v1"
          docker-image: "setthapong/bsapp:latest"

      - name: Push Image to Docker Hub 
        run: |
          docker push setthapong/bsapp:latest
